server:
  port: 8082
  servlet:
    context-path: /security
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tt?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
mybatis:
  type-aliases-package: tech.aistar.entity
  configuration:
#    开启驼峰命名
    map-underscore-to-camel-case: true
